export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-[980px] space-y-8 pb-16">
      <div>
        <p className="text-xs font-medium uppercase tracking-[0.14em] text-primary/80">Legal</p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-1 text-muted-foreground">Last updated: April 8, 2026</p>
      </div>

      <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Tailor ("the Service"), you agree to be bound by these Terms of
            Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">2. Description of Service</h2>
          <p>
            Tailor is an AI-powered resume optimization tool that analyzes your resume against job
            descriptions to identify keyword gaps, assess ATS compatibility, and generate tailored
            rewrite suggestions. The Service is provided via the website at trytailor.cv.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">3. Account Registration</h2>
          <p>
            To use certain features, you must sign in using a Google account. You are responsible
            for maintaining the confidentiality of your account and for all activities that occur
            under it. You agree to provide accurate and complete information during registration.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">4. Tokens and Usage</h2>
          <p>
            New accounts receive 5 free credits upon sign-up. Credits are consumed when you perform
            resume analyses. Token balances are non-transferable and have no monetary value. We
            reserve the right to modify token pricing or allocation at any time with reasonable
            notice.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">5. User Content</h2>
          <p>
            You retain ownership of any resume content, job descriptions, or other materials you
            submit to the Service ("User Content"). By submitting User Content, you grant Tailor a
            limited, non-exclusive license to process and analyze that content solely for the purpose
            of providing the Service to you. We do not use your User Content to train AI models.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="ml-4 list-disc space-y-1 pl-2">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the Service</li>
            <li>Submit content that infringes on third-party intellectual property rights</li>
            <li>Attempt to gain unauthorized access to any part of the Service</li>
            <li>Use automated means to access the Service without prior written consent</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">7. AI-Generated Content</h2>
          <p>
            Rewrite suggestions and analysis results are generated by AI and are provided for
            informational purposes only. Tailor does not guarantee employment outcomes. You are
            solely responsible for reviewing and approving any changes to your resume before
            submission to employers.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">8. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" without warranties of any kind, either express or
            implied. Tailor does not warrant that the Service will be uninterrupted, error-free, or
            that any specific results will be achieved through use of the Service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">9. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, Tailor shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from your use of, or
            inability to use, the Service.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Service at any time for
            violation of these Terms or for any other reason at our discretion. You may delete your
            account at any time via the Settings page.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes
            are posted constitutes acceptance of the revised Terms. We will notify you of significant
            changes via the email associated with your account.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">12. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with applicable law. Any disputes
            arising under these Terms shall be resolved through good-faith negotiation, and if
            necessary, through the courts of competent jurisdiction.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-foreground">13. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at{' '}
            <a href="mailto:marko@trytailor.cv" className="text-primary underline-offset-4 hover:underline">
              marko@trytailor.cv
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
