'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function HelpPage() {
  const faqs = [
    {
      question: "What is ATS compliance?",
      answer: "ATS (Applicant Tracking System) compliance refers to how easily a resume can be parsed and understood by the automated software used by recruiters to filter candidates. Our tool checks for common formatting and keyword issues."
    },
    {
      question: "How is the Match Score calculated?",
      answer: "The Match Score is calculated based on keyword density, relevance of experience bullet points to the job description, and overall formatting/structure checks."
    },
    {
      question: "Why should I use the Rewrite Suggestions?",
      answer: "Rewrite suggestions are generated by a language model to transform your resume bullets from descriptive to action-oriented, quantifiable statements, which are highly preferred by recruiters and ATS systems."
    },
  ];

  return (
    <div className="mx-auto w-full max-w-[980px] space-y-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-[0.14em] text-primary/80">Support</p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">Help & FAQ</h1>
        <p className="mt-1 text-muted-foreground">Find answers to common questions about the Resume Tailor tool.</p>
      </div>

      <div className="space-y-6">
        {faqs.map((faq, index) => (
          <Card key={index} className="border-border/80 bg-card/85">
            <CardHeader>
              <CardTitle className="text-lg">{faq.question}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">{faq.answer}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="mt-10 border-t border-border pt-4">
        <h2 className="text-xl font-semibold">Need more help?</h2>
        <p className="mt-2 text-muted-foreground">
          If you can&apos;t find an answer here, please contact support at marko@trytailor.cv.
        </p>
      </div>
    </div>
  );
}
